### ISSUE TITLE
Problem with xlanguage tags

### ISSUE THREAD

**Issue by liomj** [XoopsModules25x/xoopsfaq#10]
When using xlanguange tags eg [en]...[/en][ms]..[/ms] in the xoops faq, such as in categories and answers the [] tags is display instead of translating in frontend and backend

 XOOPS FAQ 2.01 Alpha 1 (01/07/2020)
Xlanguage 3.1.3 RC-1 (08/18/2021) 

<html><body>

XOOPS Version | XOOPS 2.5.11-Beta2
-- | --
PHP Version | 7.4.24
MySQL Version | 5.7.36

</body>
</html>

**Comment by mambax7** [comment]
I've made some updates in [my repository](https://github.com/mambax7/xoopsfaq), but it seems like we are still having problems with xLanguage, i.e. sometimes you have to click on the flag in order to see the the language without the tags. 

But check out the changes that I've  made - when I click on the flag, it works on the front end.

**Comment by liomj** [comment]
thank you @mambax7  your update fixed the problem in front end and back end

**Comment by mambax7** [comment]
I am glad to hear it! 
If it works now, can you close it?
